parameters:
#    application_config.example.class: Application\ConfigBundle\Example

services:
#    application_config.example:
#        class: %application_config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    application_config.admin.setting:
        class: Application\ConfigBundle\Admin\SettingAdmin
        arguments: [~, Craue\ConfigBundle\Entity\Setting, ApplicationConfigBundle:SettingAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Setting Admin}
    application_config.setting:
        class: Application\ConfigBundle\Admin\SettingEditAdmin
        arguments: [~, ~, ApplicationConfigBundle:SettingEditAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Setting Edit}
