parameters:

services:
    brother_config.admin.setting:
        class: Brother\ConfigBundle\Admin\SettingAdmin
        arguments: [ ~, Brother\ConfigBundle\Entity\Setting, BrotherConfigBundle:SettingAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Setting Admin }
    brother_config.setting:
        class: Brother\ConfigBundle\Admin\SettingEditAdmin
        arguments: [ ~, ~, BrotherConfigBundle:SettingEditAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Setting Edit }
    brother_config.cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: [%kernel.cache_dir%/brother_settings]