language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="2.3.*"

matrix:
  include:
    - php: 5.3
      env: SYMFONY_VERSION="2.1.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.1.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.2.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.4.*"
    - php: 5.5
      env: SYMFONY_VERSION="2.5.*"
    - php: 5.5
      env: SYMFONY_VERSION="dev-master" MIN_STABILITY="dev"
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION="dev-master" MIN_STABILITY="dev"

install:
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi;'
  - sh travis_install_dependencies.sh

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

notifications:
  email:
    on_success: always
    on_failure: always
